"""empty message

Revision ID: 11171784fcc2
Revises: 
Create Date: 2023-06-16 17:06:30.860957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11171784fcc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id_kategori', sa.String(), nullable=False),
    sa.Column('nama_kategori', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_kategori')
    )
    op.create_table('pengguna',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('kontak', sa.String(), nullable=True),
    sa.Column('tipe', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('penulis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('kebangsaan', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('judul', sa.String(), nullable=False),
    sa.Column('id_penulis', sa.String(), nullable=False),
    sa.Column('id_kategori', sa.String(), nullable=True),
    sa.Column('tgl_terbit', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategori.id_kategori'], ),
    sa.ForeignKeyConstraint(['id_penulis'], ['penulis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buku')
    op.drop_table('penulis')
    op.drop_table('pengguna')
    op.drop_table('kategori')
    # ### end Alembic commands ###
