"""empty message

Revision ID: f96cc1e82979
Revises: 
Create Date: 2023-06-16 16:11:16.858801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96cc1e82979'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id_kategori', sa.String(), nullable=False),
    sa.Column('nama_kategori', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_kategori')
    )
    with op.batch_alter_table('buku', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'penulis', ['id_penulis'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buku', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('kategori')
    # ### end Alembic commands ###
